-- local _, coc = pcall(require, "coc")
-- if not _ then
--   vim.notify("Not found coc module!")
--   return
-- end

-- vim.g.coc_global_extensions = {
--   'coc-marketplace',
--   'coc-json',
--   'coc-vimlsp'
--
-- }
