require('base.keymaps')
require('base.options')
require('base.plugin')


require('theme.tokyonight')

require("plugins.lsp")
require("plugins.neo-tree")
require("plugins.nvim-cmp")
require("plugins.nvim-lspconfig")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.nvim-treesitter")
require("plugins.translator")
require("plugins.telescope")
require("plugins.autopairs")
require("plugins.lspsaga")
require("plugins.indent-blankline")
require("plugins.yanky")
require("plugins.lsp-signature")
require("plugins.diagflow")
require("plugins.noice")
require("plugins.nvim-dap")
require("plugins.trouble")
require("plugins.twilight")
require("plugins.toggle_term")
require("plugins.todo-comments")
